services:
  mongodb:
    image: mongo:7.0
    container_name: medigest_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - medigest_net
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  app:
    build: .
    container_name: medigest_app
    ports:
      - "8501:8501"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - .:/app  # Mount current directory for live editing
    networks:
      - medigest_net

volumes:
  mongodb_data:

networks:
  medigest_net:
